### PR TITLE
Don't adjust SDK constraints whose min versions are prerelease

### LINKED ISSUE #1770: Invalid argument(s): Minimum version ("2.0.0-dev.15.0") must be less than maximum ("2.0.0-dev.14.0").
Running `pub --trace upgrade` causes this exception

[log.txt](https://github.com/dart-lang/pub/files/1600816/log.txt)

`pub get` (with existing `pubspec.lock`) completes without an error.

### PR DESCRIPTION
**Pull request by nex3**
Previously, if the user was using 1.2.3-dev.1 and a package had an SDK
constraint ">=1.2.3-dev.2", we would try to create an invalid
">=1.2.3-dev.2 <1.2.3-dev.1" constraint.

Closes #1770

### CODE REVIEW

File: lib/src/pubspec.dart [hunk 1]
```diff
@@ -391,6 +391,7 @@ class Pubspec {
     if (!allowPreReleaseSdk) return false;
     if (!sdk.version.isPreRelease) return false;
     if (sdkConstraint.includeMax) return false;
+    if (sdkConstraint.min?.isPreRelease ?? false) return false;
```
Comment (munificent) [inline lib/src/pubspec.dart]: Maybe it's just me, but I think this would be easier to read as the more explicit:

```dart
if (sdkConstraint.min != null && sdkConstraint.min.isPreRelease) {
  return false;
}
```

Comment (nex3) [reply lib/src/pubspec.dart]: Done.
