### PR TITLE
Emit exit code 69 for TlsExceptions

### LINKED ISSUE #1729: "Connection terminated during handshake" doesn't return error code 69
Seen during a Flutter test run:
```
02:01 +154: test/commands/create_test.dart: create project with-driver-test
Connection terminated during handshake
---- Log transcript ----
FINE: Pub 1.25.0-dev.11.0
MSG : Resolving dependencies...
SLVR: Solving dependencies:
 | - cupertino_icons ^0.1.0 from hosted (cupertino_icons)
 | - flutter any from sdk (flutter)
IO : Get versions from https://pub.dartlang.org/api/packages/cupertino_icons.
IO : HTTP GET https://pub.dartlang.org/api/packages/cupertino_icons
 | Accept: application/vnd.pub.v2+json
 | X-Pub-OS: macos
 | X-Pub-Command: get
 | X-Pub-Session-ID: 380C7AF6-F1D7-4726-BBA5-9A2C6B5C0841
 | X-Pub-Environment: flutter_bot:flutter_cli
 | X-Pub-Reason: direct
 | user-agent: Dart pub 1.25.0-dev.11.0
SLVR: Could not get versions for cupertino_icons from hosted:
 | HandshakeException: Connection terminated during handshake
 |
 | package:pub/src/source/hosted.dart 338 BoundHostedSource._throwFriendlyError
 | package:pub/src/source/hosted.dart 140 BoundHostedSource.doGetVersions
 | package:pub/src/source.dart 165 BoundSource.getVersions
 | package:pub/src/solver/version_solver.dart 231 SolverCache.getVersions.<fn>
 | dart:async runZoned
 | package:pub/src/http.dart 228 withDependencyType
 | package:pub/src/solver/version_solver.dart 230 SolverCache.getVersions
 | package:pub/src/solver/unselected_package_queue.dart 121 UnselectedPackageQueue._getNumVersions
 | package:pub/src/solver/unselected_package_queue.dart 50 UnselectedPackageQueue.add
 | package:pub/src/solver/version_selection.dart 68 VersionSelection.select.<fn>
 | dart:async Future.forEach
 | package:pub/src/solver/version_selection.dart 61 VersionSelection.select
 | package:pub/src/solver/backtracking_solver.dart 172 BacktrackingSolver.solve
 | package:pub/src/solver/version_solver.dart 42 resolveVersions.<fn>
 | package:pub/src/log.dart 409 progress
 | package:pub/src/solver/version_solver.dart 40 resolveVersions
 | package:pub/src/entrypoint.dart 193 Entrypoint.acquireDependencies
 | package:pub/src/command/get.dart 38 GetCommand.run
 | package:args/command_runner.dart 194 CommandRunner.runCommand
 | package:pub/src/command_runner.dart 168 PubCommandRunner.runCommand.<fn>
 | dart:async new Future.sync
 | package:pub/src/utils.dart 102 captureErrors.<fn>
 | package:stack_trace Chain.capture
 | package:pub/src/utils.dart 117 captureErrors
 | package:pub/src/command_runner.dart 168 PubCommandRunner.runCommand
 | package:pub/src/command_runner.dart 117 PubCommandRunner.run
 | /b/build/slave/dart-sdk-mac-dev/build/sdk/third_party/pkg/pub/bin/pub.dart 8 main
 | ===== asynchronous gap ===========================
 | dart:async _Completer.completeError
 | package:pub/src/source/hosted.dart 153 BoundHostedSource.doGetVersions
 | ===== asynchronous gap ===========================
 | dart:async _asyncErrorWrapperHelper
 | package:pub/src/source/hosted.dart 129 BoundHostedSource.doGetVersions
 | package:pub/src/source.dart 165 BoundSource.getVersions
 | package:pub/src/solver/version_solver.dart 231 SolverCache.getVersions.<fn>
 | dart:async runZoned
 | package:pub/src/http.dart 228 withDependencyType
 | package:pub/src/solver/version_solver.dart 230 SolverCache.getVersions
 | ===== asynchronous gap ===========================
 | dart:async new Future.microtask
 | package:pub/src/solver/version_solver.dart 204 SolverCache.getVersions
 | package:pub/src/solver/unselected_package_queue.dart 121 UnselectedPackageQueue._getNumVersions
 | ===== asynchronous gap ===========================
 | dart:async new Future.microtask
 | package:pub/src/solver/unselected_package_queue.dart 115 UnselectedPackageQueue._getNumVersions
 | package:pub/src/solver/unselected_package_queue.dart 50 UnselectedPackageQueue.add
 | ===== asynchronous gap ===========================
 | dart:async new Future.microtask
 | package:pub/src/solver/unselected_package_queue.dart 44 UnselectedPackageQueue.add
 | package:pub/src/solver/version_selection.dart 68 VersionSelection.select.<fn>
 | ===== asynchronous gap ===========================
 | dart:async new Future.microtask
 | package:pub/src/solver/version_selection.dart 61 VersionSelection.select.<fn>
 | dart:async Future.forEach
 | package:pub/src/solver/version_selection.dart 61 VersionSelection.select
 | ===== asynchronous gap ===========================
 | dart:async Future.forEach
 | package:pub/src/solver/version_selection.dart 61 VersionSelection.select
 | ===== asynchronous gap ===========================
 | dart:async _asyncThenWrapperHelper
 | package:pub/src/solver/version_selection.dart 53 VersionSelection.select
 | package:pub/src/solver/backtracking_solver.dart 172 BacktrackingSolver.solve
 | ===== asynchronous gap ===========================
 | dart:async new Future.microtask
 | package:pub/src/solver/backtracking_solver.dart 158 BacktrackingSolver.solve
 | package:pub/src/solver/version_solver.dart 42 resolveVersions.<fn>
 | package:pub/src/log.dart 409 progress
 | package:pub/src/solver/version_solver.dart 40 resolveVersions
 | package:pub/src/entrypoint.dart 193 Entrypoint.acquireDependencies
 | ===== asynchronous gap ===========================
 | dart:async new Future.microtask
 | package:pub/src/entrypoint.dart 192 Entrypoint.acquireDependencies
 | package:pub/src/command/get.dart 38 GetCommand.run
 | package:args/command_runner.dart 194 CommandRunner.runCommand
 | ===== asynchronous gap ===========================
 | dart:async new Future.microtask
 | package:args/command_runner.dart 142 CommandRunner.runCommand
 | package:pub/src/command_runner.dart 168 PubCommandRunner.runCommand.<fn>
 | dart:async new Future.sync
 | package:pub/src/utils.dart 102 captureErrors.<fn>
 | package:stack_trace Chain.capture
 | package:pub/src/utils.dart 117 captureErrors
 | package:pub/src/command_runner.dart 168 PubCommandRunner.runCommand
SLVR: Could not get versions for cupertino_icons from hosted:
 | HandshakeException: Connection terminated during handshake
 |
 | package:pub/src/source/hosted.dart 338 BoundHostedSource._throwFriendlyError
 | package:pub/src/source/hosted.dart 140 BoundHostedSource.doGetVersions
 | package:pub/src/source.dart 165 BoundSource.getVersions
 | package:pub/src/solver/version_solver.dart 231 SolverCache.getVersions.<fn>
 | dart:async runZoned
 | package:pub/src/http.dart 228 withDependencyType
 | package:pub/src/solver/version_solver.dart 230 SolverCache.getVersions
 | package:pub/src/solver/unselected_package_queue.dart 121 UnselectedPackageQueue._getNumVersions
 | package:pub/src/solver/unselected_package_queue.dart 50 UnselectedPackageQueue.add
 | package:pub/src/solver/version_selection.dart 68 VersionSelection.select.<fn>
 | dart:async Future.forEach
 | package:pub/src/solver/version_selection.dart 61 VersionSelection.select
 | package:pub/src/solver/backtracking_solver.dart 172 BacktrackingSolver.solve
 | package:pub/src/solver/version_solver.dart 42 resolveVersions.<fn>
 | package:pub/src/log.dart 409 progress
 | package:pub/src/solver/version_solver.dart 40 resolveVersions
 | package:pub/src/entrypoint.dart 193 Entrypoint.acquireDependencies
 | package:pub/src/command/get.dart 38 GetCommand.run
 | package:args/command_runner.dart 194 CommandRunner.runCommand
 | package:pub/src/command_runner.dart 168 PubCommandRunner.runCommand.<fn>
 | dart:async new Future.sync
 | package:pub/src/utils.dart 102 captureErrors.<fn>
 | package:stack_trace Chain.capture
 | package:pub/src/utils.dart 117 captureErrors
 | package:pub/src/command_runner.dart 168 PubCommandRunner.runCommand
 | package:pub/src/command_runner.dart 117 PubCommandRunner.run
 | /b/build/slave/dart-sdk-mac-dev/build/sdk/third_party/pkg/pub/bin/pub.dart 8 main
 | ===== asynchronous gap ===========================
 | dart:async _Completer.completeError
 | package:pub/src/source/hosted.dart 153 BoundHostedSource.doGetVersions
 | ===== asynchronous gap ===========================
 | dart:async _asyncErrorWrapperHelper
 | package:pub/src/source/hosted.dart 129 BoundHostedSource.doGetVersions
 | package:pub/src/source.dart 165 BoundSource.getVersions
 | package:pub/src/solver/version_solver.dart 231 SolverCache.getVersions.<fn>
 | dart:async runZoned
 | package:pub/src/http.dart 228 withDependencyType
 | package:pub/src/solver/version_solver.dart 230 SolverCache.getVersions
 | ===== asynchronous gap ===========================
 | dart:async new Future.microtask
 | package:pub/src/solver/version_solver.dart 204 SolverCache.getVersions
 | package:pub/src/solver/unselected_package_queue.dart 121 UnselectedPackageQueue._getNumVersions
 | ===== asynchronous gap ===========================
 | dart:async new Future.microtask
 | package:pub/src/solver/unselected_package_queue.dart 115 UnselectedPackageQueue._getNumVersions
 | package:pub/src/solver/unselected_package_queue.dart 50 UnselectedPackageQueue.add
 | ===== asynchronous gap ===========================
 | dart:async new Future.microtask
 | package:pub/src/solver/unselected_package_queue.dart 44 UnselectedPackageQueue.add
 | package:pub/src/solver/version_selection.dart 68 VersionSelection.select.<fn>
 | ===== asynchronous gap ===========================
 | dart:async new Future.microtask
 | package:pub/src/solver/version_selection.dart 61 VersionSelection.select.<fn>
 | dart:async Future.forEach
 | package:pub/src/solver/version_selection.dart 61 VersionSelection.select
 | ===== asynchronous gap ===========================
 | dart:async Future.forEach
 | package:pub/src/solver/version_selection.dart 61 VersionSelection.select
 | ===== asynchronous gap ===========================
 | dart:async _asyncThenWrapperHelper
 | package:pub/src/solver/version_selection.dart 53 VersionSelection.select
 | package:pub/src/solver/backtracking_solver.dart 172 BacktrackingSolver.solve
 | ===== asynchronous gap ===========================
 | dart:async new Future.microtask
 | package:pub/src/solver/backtracking_solver.dart 158 BacktrackingSolver.solve
 | package:pub/src/solver/version_solver.dart 42 resolveVersions.<fn>
 | package:pub/src/log.dart 409 progress
 | package:pub/src/solver/version_solver.dart 40 resolveVersions
 | package:pub/src/entrypoint.dart 193 Entrypoint.acquireDependencies
 | ===== asynchronous gap ===========================
 | dart:async new Future.microtask
 | package:pub/src/entrypoint.dart 192 Entrypoint.acquireDependencies
 | package:pub/src/command/get.dart 38 GetCommand.run
 | package:args/command_runner.dart 194 CommandRunner.runCommand
 | ===== asynchronous gap ===========================
 | dart:async new Future.microtask
 | package:args/command_runner.dart 142 CommandRunner.runCommand
 | package:pub/src/command_runner.dart 168 PubCommandRunner.runCommand.<fn>
 | dart:async new Future.sync
 | package:pub/src/utils.dart 102 captureErrors.<fn>
 | package:stack_trace Chain.capture
 | package:pub/src/utils.dart 117 captureErrors
 | package:pub/src/command_runner.dart 168 PubCommandRunner.runCommand
SLVR: * start at root
SLVR: BacktrackingSolver took 0:00:00.396383 seconds.
 | - Tried 1 solutions
 | - Requested 4 version lists
 | - Looked up 1 cached version lists
 |
FINE: Resolving dependencies finished (0.4s).
ERR : Connection terminated during handshake
FINE: Exception type: HandshakeException
FINE: package:pub/src/source/hosted.dart 338 BoundHostedSource._throwFriendlyError
 | package:pub/src/source/hosted.dart 140 BoundHostedSource.doGetVersions
 | package:pub/src/source.dart 165 BoundSource.getVersions
 | package:pub/src/solver/version_solver.dart 231 SolverCache.getVersions.<fn>
 | dart:async runZoned
 | package:pub/src/http.dart 228 withDependencyType
 | package:pub/src/solver/version_solver.dart 230 SolverCache.getVersions
 | package:pub/src/solver/unselected_package_queue.dart 121 UnselectedPackageQueue._getNumVersions
 | package:pub/src/solver/unselected_package_queue.dart 50 UnselectedPackageQueue.add
 | package:pub/src/solver/version_selection.dart 68 VersionSelection.select.<fn>
 | dart:async Future.forEach
 | package:pub/src/solver/version_selection.dart 61 VersionSelection.select
 | package:pub/src/solver/backtracking_solver.dart 172 BacktrackingSolver.solve
 | package:pub/src/solver/version_solver.dart 42 resolveVersions.<fn>
 | package:pub/src/log.dart 409 progress
 | package:pub/src/solver/version_solver.dart 40 resolveVersions
 | package:pub/src/entrypoint.dart 193 Entrypoint.acquireDependencies
 | package:pub/src/command/get.dart 38 GetCommand.run
 | package:args/command_runner.dart 194 CommandRunner.runCommand
 | package:pub/src/command_runner.dart 168 PubCommandRunner.runCommand.<fn>
 | dart:async new Future.sync
 | package:pub/src/utils.dart 102 captureErrors.<fn>
 | package:stack_trace Chain.capture
 | package:pub/src/utils.dart 117 captureErrors
 | package:pub/src/command_runner.dart 168 PubCommandRunner.runCommand
 | package:pub/src/command_runner.dart 117 PubCommandRunner.run
 | /b/build/slave/dart-sdk-mac-dev/build/sdk/third_party/pkg/pub/bin/pub.dart 8 main
 | ===== asynchronous gap ===========================
 | dart:async _Completer.completeError
 | package:pub/src/source/hosted.dart 153 BoundHostedSource.doGetVersions
 | ===== asynchronous gap ===========================
 | dart:async _asyncErrorWrapperHelper
 | package:pub/src/source/hosted.dart 129 BoundHostedSource.doGetVersions
 | package:pub/src/source.dart 165 BoundSource.getVersions
 | package:pub/src/solver/version_solver.dart 231 SolverCache.getVersions.<fn>
 | dart:async runZoned
 | package:pub/src/http.dart 228 withDependencyType
 | package:pub/src/solver/version_solver.dart 230 SolverCache.getVersions
 | ===== asynchronous gap ===========================
 | dart:async new Future.microtask
 | package:pub/src/solver/version_solver.dart 204 SolverCache.getVersions
 | package:pub/src/solver/unselected_package_queue.dart 121 UnselectedPackageQueue._getNumVersions
 | ===== asynchronous gap ===========================
 | dart:async new Future.microtask
 | package:pub/src/solver/unselected_package_queue.dart 115 UnselectedPackageQueue._getNumVersions
 | package:pub/src/solver/unselected_package_queue.dart 50 UnselectedPackageQueue.add
 | ===== asynchronous gap ===========================
 | dart:async new Future.microtask
 | package:pub/src/solver/unselected_package_queue.dart 44 UnselectedPackageQueue.add
 | package:pub/src/solver/version_selection.dart 68 VersionSelection.select.<fn>
 | ===== asynchronous gap ===========================
 | dart:async new Future.microtask
 | package:pub/src/solver/version_selection.dart 61 VersionSelection.select.<fn>
 | dart:async Future.forEach
 | package:pub/src/solver/version_selection.dart 61 VersionSelection.select
 | ===== asynchronous gap ===========================
 | dart:async Future.forEach
 | package:pub/src/solver/version_selection.dart 61 VersionSelection.select
 | ===== asynchronous gap ===========================
 | dart:async _asyncThenWrapperHelper
 | package:pub/src/solver/version_selection.dart 53 VersionSelection.select
 | package:pub/src/solver/backtracking_solver.dart 172 BacktrackingSolver.solve
 | ===== asynchronous gap ===========================
 | dart:async new Future.microtask
 | package:pub/src/solver/backtracking_solver.dart 158 BacktrackingSolver.solve
 | package:pub/src/solver/version_solver.dart 42 resolveVersions.<fn>
 | package:pub/src/log.dart 409 progress
 | package:pub/src/solver/version_solver.dart 40 resolveVersions
 | package:pub/src/entrypoint.dart 193 Entrypoint.acquireDependencies
 | ===== asynchronous gap ===========================
 | dart:async new Future.microtask
 | package:pub/src/entrypoint.dart 192 Entrypoint.acquireDependencies
 | package:pub/src/command/get.dart 38 GetCommand.run
 | package:args/command_runner.dart 194 CommandRunner.runCommand
 | ===== asynchronous gap ===========================
 | dart:async new Future.microtask
 | package:args/command_runner.dart 142 CommandRunner.runCommand
 | package:pub/src/command_runner.dart 168 PubCommandRunner.runCommand.<fn>
 | dart:async new Future.sync
 | package:pub/src/utils.dart 102 captureErrors.<fn>
 | package:stack_trace Chain.capture
 | package:pub/src/utils.dart 117 captureErrors
 | package:pub/src/command_runner.dart 168 PubCommandRunner.runCommand
---- End log transcript ----
02:02 +154 -1: test/commands/create_test.dart: create project with-driver-test [E]
 Exception: pub get failed (1)
 package:flutter_tools/src/base/common.dart 29:3 throwToolExit
 package:flutter_tools/src/dart/pub.dart 116:5 pub
 package:flutter_tools/src/dart/pub.dart 60:13 pubGet
 package:flutter_tools/src/commands/create.dart 218:13 CreateCommand.runCommand
 package:flutter_tools/src/runner/flutter_command.dart 253:18 FlutterCommand.verifyThenRunCommand
 package:flutter_tools/src/runner/flutter_command.dart 193:29 FlutterCommand.run
 package:args/command_runner.dart 194:27 CommandRunner.runCommand
 package:flutter_tools/src/runner/flutter_command_runner.dart 279:27 FlutterCommandRunner.runCommand
 package:args/command_runner.dart 109:29 CommandRunner.run.<fn>
 dart:async new Future.sync
 package:args/command_runner.dart 109:11 CommandRunner.run
 package:flutter_tools/src/runner/flutter_command_runner.dart 162:21 FlutterCommandRunner.run
 test/commands/create_test.dart 294:16 _createProject
 test/commands/create_test.dart 307:9 _createAndAnalyzeProject
 test/commands/create_test.dart 164:14 main.<fn>.<fn>
 test/src/context.dart 102:32 testUsingContext.<fn>.<fn>
 package:flutter_tools/src/base/context.dart 76:26 AppContext._run
 package:flutter_tools/src/base/context.dart 66:13 AppContext.runInZone.<fn>
 dart:async runZoned
 package:flutter_tools/src/base/context.dart 65:12 AppContext.runInZone
 test/src/context.dart 91:32 testUsingContext.<fn>
 ===== asynchronous gap ===========================
 dart:async _Completer.completeError
 package:flutter_tools/src/dart/pub.dart 117:1 pub
 ===== asynchronous gap ===========================
 dart:async _asyncThenWrapperHelper
 package:flutter_tools/src/dart/pub.dart 93:10 pub
 package:flutter_tools/src/dart/pub.dart 60:13 pubGet
 ===== asynchronous gap ===========================
 dart:async new Future.microtask
 package:flutter_tools/src/dart/pub.dart 38:10 pubGet
 package:flutter_tools/src/commands/create.dart 218:13 CreateCommand.runCommand
 ===== asynchronous gap ===========================
 dart:async _asyncThenWrapperHelper
 package:flutter_tools/src/commands/create.dart 89:35 CreateCommand.runCommand
 package:flutter_tools/src/runner/flutter_command.dart 253:18 FlutterCommand.verifyThenRunCommand
 ===== asynchronous gap ===========================
 dart:async _asyncThenWrapperHelper
 package:flutter_tools/src/runner/flutter_command.dart 233:61 FlutterCommand.verifyThenRunCommand
 package:flutter_tools/src/runner/flutter_command.dart 193:29 FlutterCommand.run
 ===== asynchronous gap ===========================
 dart:async new Future.microtask
 package:flutter_tools/src/runner/flutter_command.dart 185:28 FlutterCommand.run
 package:args/command_runner.dart 194:27 CommandRunner.runCommand
 ===== asynchronous gap ===========================
 dart:async new Future.microtask
 package:args/command_runner.dart 142:58 CommandRunner.runCommand
 package:flutter_tools/src/runner/flutter_command_runner.dart 279:27 FlutterCommandRunner.runCommand
 ===== asynchronous gap ===========================
 dart:async _asyncThenWrapperHelper
 package:flutter_tools/src/runner/flutter_command_runner.dart 166:59 FlutterCommandRunner.runCommand
 package:args/command_runner.dart 109:29 CommandRunner.run.<fn>
 dart:async new Future.sync
 package:args/command_runner.dart 109:11 CommandRunner.run
 package:flutter_tools/src/runner/flutter_command_runner.dart 162:21 FlutterCommandRunner.run
 test/commands/create_test.dart 294:16 _createProject
 ===== asynchronous gap ===========================
 dart:async new Future.microtask
 test/commands/create_test.dart 287:84 _createProject
 test/commands/create_test.dart 307:9 _createAndAnalyzeProject
 ===== asynchronous gap ===========================
 dart:async new Future.microtask
 test/commands/create_test.dart 306:85 _createAndAnalyzeProject
 test/commands/create_test.dart 164:14 main.<fn>.<fn>
 ===== asynchronous gap ===========================
 dart:async new Future.microtask
 test/commands/create_test.dart 163:59 main.<fn>.<fn>
 test/src/context.dart 102:32 testUsingContext.<fn>.<fn>
 ===== asynchronous gap ===========================
 dart:async new Future.microtask
 test/src/context.dart 91:51 testUsingContext.<fn>.<fn>
 package:flutter_tools/src/base/context.dart 76:26 AppContext._run
 ===== asynchronous gap ===========================
 dart:async new Future.microtask
 package:flutter_tools/src/base/context.dart 72:48 AppContext._run
 package:flutter_tools/src/base/context.dart 66:13 AppContext.runInZone.<fn>
 dart:async runZoned
 package:flutter_tools/src/base/context.dart 65:12 AppContext.runInZone
 test/src/context.dart 91:32 testUsingContext.<fn>
 ===== asynchronous gap ===========================
 dart:async new Future.microtask
 test/src/context.dart 73:30 testUsingContext.<fn>
02:02 +154 -1: test/commands/create_test.dart: create content
```

### PR DESCRIPTION
**Pull request by nex3**
Closes #1729

### CODE REVIEW

File: lib/src/source/hosted.dart [hunk 1]
```diff
@@ -329,7 +329,7 @@ class BoundHostedSource extends CachedSource {
           stackTrace);
     }
 
-    if (error is io.SocketException) {
+    if (error is io.SocketException || error is io.TlsException) {
       fail("Got socket error trying to find package $package at $url.", error,
```
Comment (munificent) [inline lib/src/source/hosted.dart]: It would be good to have a more specific error message, like "Got TLS error ..." if it's a TlsException.

Comment (nex3) [reply lib/src/source/hosted.dart]: Done.
