### PR TITLE
pub upgrade foo, only unlocks foo from pubspec.lock

### LINKED ISSUE #2629: `pub downgrade <package>` does not respect version constraints
# Environment

- `pub version` or `flutter pub version`: Pub 2.9.1

# Problem

Downgrade does not respect version constraints. For example, in the following test:

```dart
void main() {
  test('downgrade test', () async {
    await servePackages((builder) {
      builder.serve('foo', '2.0.0');
      builder.serve('foo', '1.0.0');
    });

    await d.appDir({'foo': '^2.0.0'}).create();

    await pubGet();

    await d.appPackagesFile({'foo': '2.0.0'}).validate();

    await pubDowngrade(args: ['foo']);
  });
}
```

## Expected behavior

Expected the test to pass without issues (i.e.`foo` remains at `2.0.0`).

## Actual behavior

The version solver tries to force version `1.0.0` of `foo`.

## --trace output

```
Process `pub downgrade` exited with exitCode 1. Output:
[e] FINE: Pub 0.1.2+3
    MSG : Resolving dependencies...
[e] SLVR: fact: myapp is 0.0.0
[e] SLVR: derived: myapp
[e] SLVR: fact: myapp depends on foo ^2.0.0
[e] SLVR:   selecting myapp
[e] SLVR:   derived: foo ^2.0.0
[e] IO  : Get versions from http://localhost:34275/api/packages/foo.
[e] IO  : HTTP GET http://localhost:34275/api/packages/foo
[e]     | Accept: application/vnd.pub.v2+json
[e]     | X-Pub-OS: linux
[e]     | X-Pub-Command: downgrade
[e]     | X-Pub-Session-ID: 5CB6D4C0-A1E0-4C2F-A78B-21AAFC85ABEF
[e]     | X-Pub-Environment: test-environment
[e]     | X-Pub-Reason: direct
[e]     | user-agent: Dart pub 0.1.2+3
[e] IO  : HTTP response 200 OK for GET http://localhost:34275/api/packages/foo
[e]     | took 0:00:00.043943
[e]     | transfer-encoding: chunked
[e]     | date: Fri, 21 Aug 2020 13:38:30 GMT
[e]     | x-frame-options: SAMEORIGIN
[e]     | content-type: text/plain; charset=utf-8
[e]     | x-xss-protection: 1; mode=block
[e]     | x-content-type-options: nosniff
[e]     | server: dart:io with Shelf
[e] SLVR:   fact: the latest version of foo (1.0.0) is required
[e] SLVR:   conflict: the latest version of foo (1.0.0) is required
[e] SLVR:   ! foo <1.0.0-∞ or >1.0.0 is satisfied by foo ^2.0.0
[e] SLVR:   ! which is caused by "myapp depends on foo ^2.0.0"
[e] SLVR:   ! thus: version solving failed
[e] SLVR: Version solving took 0:00:00.104559 seconds.
[e]     | Tried 1 solutions.
[e] FINE: Resolving dependencies finished (0.122s).
[e] ERR : Because myapp depends on foo <1.0.0-∞ or >1.0.0 but the latest version (1.0.0) is required, version solving failed.
[e] FINE: Exception type: SolveFailure
[e] FINE: package:pub/src/solver/version_solver.dart 312:5   VersionSolver._resolveConflict
[e]     | package:pub/src/solver/version_solver.dart 133:27  VersionSolver._propagate
[e]     | package:pub/src/solver/version_solver.dart 97:11   VersionSolver.solve.<fn>
[e]     | ===== asynchronous gap ===========================
[e]     | dart:async                                         Future.catchError
[e]     | package:pub/src/utils.dart 113:52                  captureErrors.wrappedCallback
[e]     | package:stack_trace                                Chain.capture
[e]     | package:pub/src/utils.dart 126:11                  captureErrors
[e]     | package:pub/src/command_runner.dart 182:13         PubCommandRunner.runCommand

```

## Notes

Upon inspection, it is likely that the issue is caused by `useLatest` in `acquireDependencies`, which forces the oldest version regardless of constraint on `pubspec.yaml` in `packageLister.bestVersion`.

### LINKED ISSUE #2630: `pub upgrade <package>` does not respect version constraints
# Environment

- `pub version` or `flutter pub version`: Pub 2.9.1

# Problem

`pub upgrade <package>` does not seem to be respecting version constraints, for example in the following test: 

```dart
void main() {
  test('upgrade test', () async {
    await servePackages((builder) {
      builder.serve('foo', '1.0.0');
    });

    await d.appDir({'foo': '^1.0.0'}).create();

    await pubGet();

    await d.appPackagesFile({'foo': '1.0.0'}).validate();

    globalPackageServer.add((builder) {
      builder.serve('foo', '1.5.0');
      builder.serve('foo', '2.0.0');
    });

    await pubUpgrade(args: ['foo']);
  });
}
```

## Expected behavior

Expected the test to pass without issues, with `foo` getting bumped to `1.5.0`.

## Actual behavior

The version solver tries to force version `2.0.0` of `foo`.

## --trace output

```
[e] FINE: Pub 0.1.2+3
    MSG : Resolving dependencies...
[e] SLVR: fact: myapp is 0.0.0
[e] SLVR: derived: myapp
[e] SLVR: fact: myapp depends on foo ^1.0.0
[e] SLVR:   selecting myapp
[e] SLVR:   derived: foo ^1.0.0
[e] IO  : Get versions from http://localhost:44351/api/packages/foo.
[e] IO  : HTTP GET http://localhost:44351/api/packages/foo
[e]     | Accept: application/vnd.pub.v2+json
[e]     | X-Pub-OS: linux
[e]     | X-Pub-Command: upgrade
[e]     | X-Pub-Session-ID: A8B4AB61-AED0-4464-8A5B-AFE54C9F820F
[e]     | X-Pub-Environment: test-environment
[e]     | X-Pub-Reason: direct
[e]     | user-agent: Dart pub 0.1.2+3
[e] IO  : HTTP response 200 OK for GET http://localhost:44351/api/packages/foo
[e]     | took 0:00:00.041970
[e]     | transfer-encoding: chunked
[e]     | date: Fri, 21 Aug 2020 13:48:30 GMT
[e]     | x-frame-options: SAMEORIGIN
[e]     | content-type: text/plain; charset=utf-8
[e]     | x-xss-protection: 1; mode=block
[e]     | x-content-type-options: nosniff
[e]     | server: dart:io with Shelf
[e] SLVR:   fact: the latest version of foo (2.0.0) is required
[e] SLVR:   conflict: the latest version of foo (2.0.0) is required
[e] SLVR:   ! foo <2.0.0-∞ or >2.0.0 is satisfied by foo ^1.0.0
[e] SLVR:   ! which is caused by "myapp depends on foo ^1.0.0"
[e] SLVR:   ! thus: version solving failed
[e] SLVR: Version solving took 0:00:00.100353 seconds.
[e]     | Tried 1 solutions.
[e] FINE: Resolving dependencies finished (0.116s).
[e] ERR : Because myapp depends on foo <2.0.0-∞ or >2.0.0 but the latest version (2.0.0) is required, version solving failed.
[e] FINE: Exception type: SolveFailure
[e] FINE: package:pub/src/solver/version_solver.dart 312:5   VersionSolver._resolveConflict
[e]     | package:pub/src/solver/version_solver.dart 133:27  VersionSolver._propagate
[e]     | package:pub/src/solver/version_solver.dart 97:11   VersionSolver.solve.<fn>
[e]     | ===== asynchronous gap ===========================
[e]     | dart:async                                         Future.catchError
[e]     | package:pub/src/utils.dart 113:52                  captureErrors.wrappedCallback
[e]     | package:stack_trace                                Chain.capture
[e]     | package:pub/src/utils.dart 126:11                  captureErrors
[e]     | package:pub/src/command_runner.dart 182:13         PubCommandRunner.runCommand

```
## Notes

Upon inspection, it is likely that the issue is caused by `useLatest` in `acquireDependencies`, which forces the newest version regardless of constraint on `pubspec.yaml` in `packageLister.bestVersion`.

### PR DESCRIPTION
**Pull request by jonasfj**
Fixes #2629
Fixes #2630

TODO:
 * [ ] Add test for #2629

### CODE REVIEW

File: lib/src/solver.dart [hunk 1]
```diff
@@ -46,17 +52,27 @@ Future<SolveResult> resolveVersions(
 /// Like [resolveVersions] except that this function returns `null` where a
 /// similar call to [resolveVersions] would throw a [SolveFailure].
 ///
-/// If [useLatest] is given, then only the latest versions of the referenced
-/// packages will be used. This is for forcing an upgrade to one or more
-/// packages.
+/// If [unlock] is given, then packages listed in [unlock] will not be unlocked
```
Comment (sigurdm) [inline lib/src/solver.dart:55]:
```suggestion
/// If [unlock] is given, only packages listed in [unlock] will be unlocked
```

File: lib/src/solver.dart [hunk 2]
```diff
@@ -21,20 +21,26 @@ export 'solver/type.dart';
 /// that those dependencies place on each other and the requirements imposed by
 /// [lockFile].
 ///
-/// If [useLatest] is given, then only the latest versions of the referenced
-/// packages will be used. This is for forcing an upgrade to one or more
-/// packages.
+/// If [unlock] is given, then packages listed in [unlock] will not be unlocked
```
Comment (sigurdm) [inline lib/src/solver.dart:24]:
```suggestion
/// If [unlock] is given, then only packages listed in [unlock] will be unlocked
```

**Review by sigurdm — APPROVED** [review]
LGTM except for typos in comments
