### PR TITLE
Fixed bug in adding dependency to empty dependencies key

### LINKED ISSUE #2637: pub add <package> with empty `dependencies` key
```
name: mypkg
dependencies:
environment:
  sdk: ^2.9.0-edge
dev_dependencies: {}
```
Then run:
```
[mypkg]$pub add retry
Error on line 3, column 27: Mapping values are not allowed here. Did you miss a colon earlier?
  ╷
3 │   retry: ^3.0.1environment:
  │                           ^
  ╵
```

We have two problems here.

 1. A bug in `yaml_edit`,
 2. A bug in how `pub add` catches `AssertionError`, I assume this an internal assertion in `yaml_edit` that fails.

I think it's best if `pub add` catches `AssertionError` and shows a message where it says to report it here.
We have other places where we handle internal errors and have a message.

Side note: We should probably make methods that modify `pubspec.yaml` log contents of `pubspec.yaml` as well as the change they are doing. We can log it such it only shows up with `--verbose`

### PR DESCRIPTION
**Pull request by walnutdust**
See https://github.com/google/dart-neats/pull/63 for associated tests

Closes #2637

### CODE REVIEW

File: lib/src/command/add.dart [hunk 1]
```diff
@@ -389,13 +391,17 @@ class AddCommand extends PubCommand {
           packagePath, pubspecInformation ?? '^${resultPackage.version}');
     }
 
+    log.fine('Added ^${resultPackage.version} to "$dependencyKey"');
```
Comment (jonasfj) [inline lib/src/command/add.dart:394]: This is not what happens if adding a git dependency... etc.. I'm fine with a dumber message that just says:
`Added "${package.name}" to $dependencyKey`.

File: lib/src/command/add.dart [hunk 2]
```diff
@@ -389,13 +391,17 @@ class AddCommand extends PubCommand {
...
+
     /// Remove the package from dev_dependencies if we are adding it to
     /// dependencies. Refer to [_addPackageToPubspec] for additional discussion.
     if (!isDevelopment &&
         yamlEditor.parseAt(['dev_dependencies', package.name],
                 orElse: () => null) !=
             null) {
       yamlEditor.remove(['dev_dependencies', package.name]);
+
+      log.fine('Removed ^${resultPackage.version} from "dev_dependencies".');
```
Comment (jonasfj) [inline lib/src/command/add.dart:404]: Again, let's just say package name and `dev_dependencies`, and avoiding mentioning the constraint we removed.. because unless we want to make a lot of logic to log the right thing.

**Review by jonasfj — APPROVED** [review]
